package com.fleetlize.webapp.gateways.database;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class Queries {

  public static final String INSERT_CAR_MODEL = "INSERT INTO CAR_MODEL (MANUFACTURER_ID, MODEL_NAME, CREATION_DATE, MODEL_YEAR, CATEGORY_ID) " +
      "VALUES (:MANUFACTURER_ID, :MODEL_NAME, :CREATION_DATE, :MODEL_YEAR, :CATEGORY_ID)";

  public static final String INSERT_CAR = "INSERT INTO CAR (PLATE, MILEAGE, CAR_MODEL_ID, CREATION_DATE) VALUES (:PLATE, :MILEAGE, :CAR_MODEL, :CREATION_DATE)";

  public static final String FIND_ALL_CAR_MODEL = "SELECT CM.CAR_MODEL_ID, CM.MANUFACTURER_ID, MA.NAME, CM.MODEL_NAME, CM.MODEL_YEAR, CM.CREATION_DATE, CM.UPDATE_DATE, CA.CATEGORY_ID, CA.CATEGORY_NAME, CA.DAILY_PRICE "
      + "FROM CAR_MODEL CM "
      + "INNER JOIN MANUFACTURER MA ON MA.MANUFACTURER_ID = CM.MANUFACTURER_ID "
      + "INNER JOIN CATEGORY  CA ON CA.CATEGORY_ID = CM.CATEGORY_ID ";

  public static final String FIND_CAR_MODEL_BY_ID = "SELECT CM.CAR_MODEL_ID, CM.MANUFACTURER_ID, MA.NAME, CM.MODEL_NAME, CM.MODEL_YEAR, CM.CREATION_DATE, CM.UPDATE_DATE, MA.CREATION_DATE AS MA_CREATION_DATE, MA.UPDATE_DATE AS MA_UPDATE_DATE, CA.CATEGORY_ID, CA.CATEGORY_NAME, CA.DAILY_PRICE "
      + "FROM CAR_MODEL CM "
      + "INNER JOIN MANUFACTURER MA ON MA.MANUFACTURER_ID = CM.MANUFACTURER_ID "
      + "INNER JOIN CATEGORY  CA ON CA.CATEGORY_ID = CM.CATEGORY_ID "
      + "WHERE CM.CAR_MODEL_ID = :ID";

  public static final String DELETE_CAR_MODEL_BY_ID = "DELETE FROM CAR_MODEL WHERE CAR_MODEL_ID = :ID";

  public static final String UPDATE_CAR_MODEL = "UPDATE CAR_MODEL SET MANUFACTURER_ID = :MANUFACTURER_ID, MODEL_NAME = :MODEL_NAME, MODEL_YEAR = :MODEL_YEAR, UPDATE_DATE = :UPDATE_DATE WHERE CAR_MODEL_ID = :ID";

  public static final String INSERT_CATEGORY = "INSERT INTO CATEGORY (CATEGORY_NAME, DAILY_PRICE) VALUES (:NAME, :DAILY_PRICE)";

  public static final String FIND_CATEGORY_BY_ID = "SELECT CATEGORY_ID, CATEGORY_NAME, DAILY_PRICE FROM CATEGORY WHERE CATEGORY_ID = :ID";

  public static final String FIND_CAR_BY_ID = "SELECT c.CAR_ID, c.PLATE, c.MILEAGE, model.CAR_MODEL_ID, model.MODEL_NAME, model.MODEL_YEAR, model.CREATION_DATE, model.UPDATE_DATE, manufacturer.NAME, manufacturer.MANUFACTURER_ID, "
      + "manufacturer.CREATION_DATE AS MA_CREATION_DATE, manufacturer.UPDATE_DATE AS MA_UPDATE_DATE, category.CATEGORY_NAME, category.DAILY_PRICE, category.CATEGORY_ID "
      + "FROM CAR c "
      + "LEFT JOIN CAR_MODEL model on model.CAR_MODEL_ID = c.CAR_MODEL_ID "
      + "LEFT JOIN MANUFACTURER manufacturer on manufacturer.MANUFACTURER_ID = model.MANUFACTURER_ID "
      + "LEFT JOIN CATEGORY category on category.CATEGORY_ID = model.CATEGORY_ID "
      + "WHERE c.CAR_ID = :ID";

  public static final String UPDATE_CAR_MODEL_CATEGORY = "UPDATE CAR_MODEL SET CATEGORY_ID = :CATEGORY_ID WHERE CAR_MODEL_ID = :CAR_MODEL_ID";

  public static final String FIND_ALL_CARS = "SELECT "
      + "car.CAR_ID, car.PLATE, car.MILEAGE, "
      + "model.CAR_MODEL_ID, model.MODEL_NAME, model.MODEL_YEAR, "
      + "category.CATEGORY_NAME, category.DAILY_PRICE, category.CATEGORY_ID, "
      + "manufacturer.MANUFACTURER_ID, manufacturer.NAME "
      + "FROM CAR car "
      + "INNER JOIN CAR_MODEL model ON model.CAR_MODEL_ID = car.CAR_MODEL_ID "
      + "INNER JOIN CATEGORY category ON category.CATEGORY_ID = model.CATEGORY_ID "
      + "INNER JOIN MANUFACTURER manufacturer ON manufacturer.MANUFACTURER_ID = model.MANUFACTURER_ID";

}
