package com.fleetlize.webapp.gateways.database;

public interface Queries {

    String INSERT_CAR_MODEL = "INSERT INTO CAR_MODEL (MANUFACTURER_ID, MODEL_NAME, CREATION_DATE, MODEL_YEAR) " +
            "VALUES (:MANUFACTURER_ID, :MODEL_NAME, :CREATION_DATE, :MODEL_YEAR)";

    String FIND_CAR_MODEL = "SELECT CM.ID AS MODEL_ID, CM.MANUFACTURER_ID, MA.NAME, CM.MODEL_NAME, CM.MODEL_YEAR, CM.CREATION_DATE, CM.UPDATE_DATE FROM CAR_MODEL CM " +
            "INNER JOIN MANUFACTURER MA ON MA.MANUFACTURER_ID = CM.MANUFACTURER_ID ";

    String FIND_CAR_MODEL_BY_ID = "SELECT CM.ID AS MODEL_ID, CM.MANUFACTURER_ID, MA.NAME, CM.MODEL_NAME, CM.MODEL_YEAR, CM.CREATION_DATE, CM.UPDATE_DATE FROM CAR_MODEL CM " +
            "INNER JOIN MANUFACTURER MA ON MA.MANUFACTURER_ID = CM.MANUFACTURER_ID WHERE CM.ID = :ID";

    String DELETE_CAR_MODEL_BY_ID = "DELETE FROM CAR_MODEL WHERE ID = :ID";

    String UPDATE_CAR_MODEL = "UPDATE CAR_MODEL SET MANUFACTURER_ID = :MANUFACTURER_ID, MODEL_NAME = :MODEL_NAME, MODEL_YEAR = :MODEL_YEAR, UPDATE_DATE = :UPDATE_DATE WHERE ID = :ID";
}
