INSERT INTO MANUFACTURER (NAME, CREATION_DATE) VALUES ('Ford', CURRENT_TIMESTAMP);
INSERT INTO CATEGORY (CATEGORY_NAME,DAILY_PRICE) VALUES ('Premium',55.32);
INSERT INTO CAR_MODEL (MANUFACTURER_ID,MODEL_NAME,MODEL_YEAR,CATEGORY_ID,CREATION_DATE,UPDATE_DATE) VALUES (1,'KA',2020,1,'2020-05-26 14:20:13.0',NULL);