name: Java CI
on: [push]
jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: compile
      - run: mvn -B compile
  test:
    name: test
    runs-on: ubuntu-latest
    steps:    
      - name: test with Maven
        run: mvn -B test
  show-tests:
    name: arquive coverage
    runs-on: ubuntu-latest
    uses: actions/upload-artifact@v1
    with:
      name: coverage-report
      path: target/site/jacoco/index.html
    
